spring:
  profiles:
    active:
      -dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

#mybatis 包扫描
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wc.springcloud.entities
  mapper-locations:
    -classpath: mybatis/mapper/**/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: wc-microservicecloud
  company.name:  www.baidu.com
  build.artifactId: $project.artifactId$
  build.vwrsion: $project.version$
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false #dev和test 连接的数据库不同
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

#mybatis 包扫描
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wc.springcloud.entities
  mapper-locations:
    -classpath: mybatis/mapper/**/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

  info.app.name= wc-microservicecloud
  info.company.name= www.baidu.com
  info.build.artifactId= $project.artifactId$
  info.build.version= $project.version$

info:
  app.name: wc-microservicecloud
  company.name:  www.baidu.com
  build.artifactId: $project.artifactId$
  build.vwrsion: $project.version$